version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=movie_expert
      - MYSQL_USER=expert
      - MYSQL_PASSWORD=expert
      - MYSQL_ROOT_PASSWORD=secure
    ports:
      - '3306:3306'
    volumes: 
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysqldata:/var/lib/mysql
volumes:
  db:
    driver: local